/*
 * Autor: Marshal Mori Cavalheiro
 * email: marshalmori@gmail.com
 * Projeto: B 305
 */

package Formularios;

import Utilitarios.Conexao;
import Utilitarios.TeclasPermitidas;
import Utilitarios.TeclasPermitidasComVirgula;
import java.io.File;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


public class TelaCadastrar extends javax.swing.JFrame {
    
    TelaInsereOriginal telaInsereOriginal = new TelaInsereOriginal();
    Conexao conexao = new Conexao();
    File [] files;
    String [] paths;
    JFileChooser chooser = new JFileChooser();
    

    public TelaCadastrar() {
        initComponents();
        conexao.conexaoBanco();
        
        jTextFieldOriginal.setEditable(false);

        
        jLabelNomeBaseObrigatorio.setVisible(false);
        jLabelVideoOriginalObrigatorio.setVisible(false);
        jLabelAlturaObrigatorio.setVisible(false);
        jLabelLarguraObrigatorio.setVisible(false);
        jLabelVideosProcessadosObrigatorio.setVisible(false);
        jButtonEditar.setVisible(false);
        
        jTextFieldAltura.setDocument(new TeclasPermitidas());
        jTextFieldLargura.setDocument(new TeclasPermitidas());
        jTextFieldTempo.setDocument(new TeclasPermitidasComVirgula());
        jTextFieldNumeroDeFrames.setDocument(new TeclasPermitidasComVirgula());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonContinuar = new javax.swing.JButton();
        jButtonFinalizar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldNomeBase = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldOrigem = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldContato = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldURL = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButtonOriginal = new javax.swing.JButton();
        jButtonProcessados = new javax.swing.JButton();
        jTextFieldOriginal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListProcessados = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jLabelNomeBaseObrigatorio = new javax.swing.JLabel();
        jLabelVideoOriginalObrigatorio = new javax.swing.JLabel();
        jLabelVideosProcessadosObrigatorio = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBoxFPS = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldAltura = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldLargura = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxSubamostragem = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldNumeroDeFrames = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jComboBoxVarredura = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        jComboBoxNrDeBits = new javax.swing.JComboBox();
        jTextFieldTempo = new javax.swing.JTextField();
        jLabelAlturaObrigatorio = new javax.swing.JLabel();
        jLabelLarguraObrigatorio = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaObservacoes = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro");
        setIconImages(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));

        jButtonContinuar.setText("Continuar");
        jButtonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinuarActionPerformed(evt);
            }
        });

        jButtonFinalizar.setText("Finalizar");
        jButtonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinalizarActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonFinalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonContinuar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButtonContinuar)
                .addGap(27, 27, 27)
                .addComponent(jButtonFinalizar)
                .addGap(28, 28, 28)
                .addComponent(jButtonEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButtonSair)
                .addGap(35, 35, 35))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setPreferredSize(new java.awt.Dimension(309, 700));

        jTextFieldNomeBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeBaseActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome da Base");

        jTextFieldOrigem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOrigemActionPerformed(evt);
            }
        });

        jLabel15.setText("Origem");

        jLabel16.setText("Contato");

        jTextFieldURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldURLActionPerformed(evt);
            }
        });

        jLabel17.setText("URL");

        jButtonOriginal.setText("Original");
        jButtonOriginal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOriginalActionPerformed(evt);
            }
        });

        jButtonProcessados.setText("Processados");
        jButtonProcessados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProcessadosActionPerformed(evt);
            }
        });

        jTextFieldOriginal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOriginalActionPerformed(evt);
            }
        });

        jLabel2.setText("Vídeo original");

        jListProcessados.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListProcessados);

        jLabel3.setText("Vídeos Processados");

        jLabelNomeBaseObrigatorio.setFont(new java.awt.Font("Dialog", 2, 10)); // NOI18N
        jLabelNomeBaseObrigatorio.setForeground(new java.awt.Color(255, 51, 51));
        jLabelNomeBaseObrigatorio.setText("Campo Obrigatório");

        jLabelVideoOriginalObrigatorio.setFont(new java.awt.Font("Dialog", 2, 10)); // NOI18N
        jLabelVideoOriginalObrigatorio.setForeground(new java.awt.Color(255, 51, 51));
        jLabelVideoOriginalObrigatorio.setText("Campo Obrigatório");

        jLabelVideosProcessadosObrigatorio.setFont(new java.awt.Font("Dialog", 2, 10)); // NOI18N
        jLabelVideosProcessadosObrigatorio.setForeground(new java.awt.Color(255, 51, 51));
        jLabelVideosProcessadosObrigatorio.setText("Campo Obrigatório");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFieldContato, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldURL, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelVideoOriginalObrigatorio))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelNomeBaseObrigatorio))
                                    .addComponent(jLabel15)
                                    .addComponent(jTextFieldOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNomeBase, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelVideosProcessadosObrigatorio))
                                    .addComponent(jButtonProcessados, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelNomeBaseObrigatorio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNomeBase, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldContato, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldURL, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelVideoOriginalObrigatorio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonOriginal)
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelVideosProcessadosObrigatorio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonProcessados)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] {" ", "YUV", "AVI", "MP4", "H264", "MKV", "TS"}));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBoxFPS.setModel(new javax.swing.DefaultComboBoxModel(new String[] {" ","25.0","50.0", "29.7", "30.0" }));
        jComboBoxFPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFPSActionPerformed(evt);
            }
        });

        jLabel8.setText("FPS");

        jLabel4.setText("Tipo vídeo");

        jLabel9.setText("Tempo (segundos)");

        jLabel5.setText("Altura");

        jTextFieldLargura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLarguraActionPerformed(evt);
            }
        });

        jLabel6.setText("Largura");

        jLabel7.setText("Subamostragem");

        jComboBoxSubamostragem.setModel(new javax.swing.DefaultComboBoxModel(new String[] {" ", "4:2:0", "4:2:2", "4:4:1", "4:4:4" }));
        jComboBoxSubamostragem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSubamostragemActionPerformed(evt);
            }
        });

        jLabel18.setText("Número de frames");

        jTextFieldNumeroDeFrames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeroDeFramesActionPerformed(evt);
            }
        });

        jLabel19.setText("Varredura");

        jComboBoxVarredura.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"","P", "I" }));

        jLabel20.setText("Nr de bits");

        jComboBoxNrDeBits.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"", "8", "16", "32"}));

        jLabelAlturaObrigatorio.setFont(new java.awt.Font("Dialog", 2, 10)); // NOI18N
        jLabelAlturaObrigatorio.setForeground(new java.awt.Color(255, 51, 51));
        jLabelAlturaObrigatorio.setText("Campo Obrigatório");

        jLabelLarguraObrigatorio.setFont(new java.awt.Font("Dialog", 2, 10)); // NOI18N
        jLabelLarguraObrigatorio.setForeground(new java.awt.Color(255, 51, 51));
        jLabelLarguraObrigatorio.setText("Campo Obrigatório");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxFPS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jComboBoxSubamostragem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelAlturaObrigatorio))
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldAltura)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelLarguraObrigatorio))
                    .addComponent(jTextFieldLargura)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldNumeroDeFrames)
                    .addComponent(jComboBoxVarredura, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxNrDeBits, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldTempo))
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabelAlturaObrigatorio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabelLarguraObrigatorio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldLargura, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxSubamostragem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxFPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNumeroDeFrames, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxVarredura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxNrDeBits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextAreaObservacoes.setColumns(20);
        jTextAreaObservacoes.setRows(5);
        jScrollPane1.setViewportView(jTextAreaObservacoes);

        jLabel10.setText("Observações");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jMenu1.setText("Cadastro");

        jMenuItem1.setText("Subamostragem");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Tipo vídeo");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("FPS");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("jMenuItem4");
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Relatórios");
        jMenuBar1.add(jMenu3);

        jMenu5.setText("Ajuda");
        jMenuBar1.add(jMenu5);

        jMenu4.setText("Sair");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(878, 760));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void fazendoStatement(){
           try {
      

                        PreparedStatement pst = conexao.con.prepareStatement("INSERT INTO BASE (nome,origem, contato, url) "
                         + "VALUES (?,?,?,?)");
                        pst.setString(1, jTextFieldNomeBase.getText());
                        pst.setString(2, jTextFieldOrigem.getText());
                        pst.setString(3, jTextFieldContato.getText());
                        pst.setString(4, jTextFieldURL.getText());
              
           
           
                       PreparedStatement pst2 = conexao.con.prepareStatement("INSERT INTO ORIGINAL (path_original, tipo_video, altura, largura, tempo, subamostragem, fps, numero_frames, varredura, nr_bits, observacao) "
                               + "VALUES (?,?,?,?,?,?,?,?,?,?,?)");
                       pst2.setString(1, jTextFieldOriginal.getText());
                       pst2.setString(2, (String) jComboBox2.getSelectedItem());
                       pst2.setInt(3, Integer.valueOf(jTextFieldAltura.getText()));
                       pst2.setInt(4, Integer.valueOf(jTextFieldLargura.getText()));
                       pst2.setString(5, jTextFieldTempo.getText());
                       pst2.setString(6, (String)jComboBoxSubamostragem.getSelectedItem());
                       pst2.setString(7, (String)jComboBoxFPS.getSelectedItem());
                       pst2.setString(8, jTextFieldNumeroDeFrames.getText());
                       pst2.setString(9, (String) jComboBoxVarredura.getSelectedItem());
                       pst2.setString(10, (String)jComboBoxNrDeBits.getSelectedItem());
                       pst2.setString(11, jTextAreaObservacoes.getText());
           
           


                        PreparedStatement pst3 = conexao.con.prepareStatement("INSERT INTO DISTORCIDOS (path_distorcido) "
                               + "VALUES (?)");       
                           for (int index = 0; index < files.length; index++) {
                                pst3.setString(1, files[index].toString());
                                pst3.executeUpdate(); //mmc - o pst3.executeUpdate está dentro do for porque tem atualizar o banco a cada inserção.
                       }  


                            pst.executeUpdate();
                            pst2.executeUpdate();
      
          

                            JOptionPane.showMessageDialog(rootPane, "Salvo com sucesso!.");
                               
                    } catch (SQLException ex) {
                            JOptionPane.showMessageDialog(rootPane, "\n Erro: " +ex);
                    }//fim do catch
    }
    
    
    
    
    private void jTextFieldNomeBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeBaseActionPerformed
        
    }//GEN-LAST:event_jTextFieldNomeBaseActionPerformed

    private void jTextFieldOriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOriginalActionPerformed
     
        
    }//GEN-LAST:event_jTextFieldOriginalActionPerformed

    private void jComboBoxSubamostragemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSubamostragemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSubamostragemActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinalizarActionPerformed
        // TODO add your handling code here:
                TelaCalcular telaCalcular = new TelaCalcular();
                telaCalcular.setVisible(true);
    }//GEN-LAST:event_jButtonFinalizarActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jButtonOriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOriginalActionPerformed
       
        try{
         chooser.showOpenDialog(null);
         File file = chooser.getSelectedFile();
         String fileAbsolutePath = file.getAbsolutePath();
         //String fileName2 = file.get
         jTextFieldOriginal.setText(fileAbsolutePath);
            
        }catch(Exception e){
            
        }
     
    }//GEN-LAST:event_jButtonOriginalActionPerformed

    private void jComboBoxFPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFPSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFPSActionPerformed

    private void jButtonProcessadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProcessadosActionPerformed

        try{
        chooser.setMultiSelectionEnabled(true);
        chooser.setFileSelectionMode(chooser.FILES_ONLY);
        chooser.showOpenDialog(null);
        
        files = chooser.getSelectedFiles();
        
        
        jListProcessados.setListData(files);
        
      
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro:"+e);
        }
        
    }//GEN-LAST:event_jButtonProcessadosActionPerformed

    private void jTextFieldOrigemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOrigemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldOrigemActionPerformed

    private void jTextFieldURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldURLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldURLActionPerformed

    private void jTextFieldLarguraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLarguraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLarguraActionPerformed

    private void jTextFieldNumeroDeFramesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeroDeFramesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeroDeFramesActionPerformed

    private void jButtonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinuarActionPerformed
//         TODO add your handling code here:
        
        
        if(jTextFieldNomeBase.getText().isEmpty()){
            jLabelNomeBaseObrigatorio.setVisible(true);
            JOptionPane.showMessageDialog(rootPane, "Nome da Base é um campo obrigatório.");
        }else if(jTextFieldOriginal.getText().isEmpty()){
                jLabelVideoOriginalObrigatorio.setVisible(true);
                JOptionPane.showMessageDialog(rootPane, "Vídeo Original é um campo obrigatório.");
        }else if(chooser.getSelectedFiles().length == 0){
                jLabelVideosProcessadosObrigatorio.setVisible(true);
                JOptionPane.showMessageDialog(rootPane, "Vídeos Processados é um campo obrigatório.");
        }else if(jTextFieldAltura.getText().isEmpty()){
                jLabelAlturaObrigatorio.setVisible(true);
                JOptionPane.showMessageDialog(rootPane, "Altura é um campo obrigatório.");
        }else if(jTextFieldLargura.getText().isEmpty()){
                jLabelLarguraObrigatorio.setVisible(true);
                JOptionPane.showMessageDialog(rootPane, "Largura é um campo obrigatório.");
        }else if(jTextFieldTempo.getText().isEmpty()){
                
                fazendoStatement();
                
                    
                
        }else{
                    jLabelNomeBaseObrigatorio.setVisible(false);
                    jLabelVideoOriginalObrigatorio.setVisible(false);
                    jLabelVideosProcessadosObrigatorio.setVisible(false);
                    jLabelAlturaObrigatorio.setVisible(false);
                    jLabelLarguraObrigatorio.setVisible(false);
                   
            fazendoStatement();
            
        }
                
    }//GEN-LAST:event_jButtonContinuarActionPerformed

    
    
    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
   

   
    

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonContinuar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonFinalizar;
    private javax.swing.JButton jButtonOriginal;
    private javax.swing.JButton jButtonProcessados;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBoxFPS;
    private javax.swing.JComboBox jComboBoxNrDeBits;
    private javax.swing.JComboBox jComboBoxSubamostragem;
    private javax.swing.JComboBox jComboBoxVarredura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAlturaObrigatorio;
    private javax.swing.JLabel jLabelLarguraObrigatorio;
    private javax.swing.JLabel jLabelNomeBaseObrigatorio;
    private javax.swing.JLabel jLabelVideoOriginalObrigatorio;
    private javax.swing.JLabel jLabelVideosProcessadosObrigatorio;
    private javax.swing.JList jListProcessados;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaObservacoes;
    private javax.swing.JTextField jTextFieldAltura;
    private javax.swing.JTextField jTextFieldContato;
    private javax.swing.JTextField jTextFieldLargura;
    private javax.swing.JTextField jTextFieldNomeBase;
    private javax.swing.JTextField jTextFieldNumeroDeFrames;
    private javax.swing.JTextField jTextFieldOrigem;
    private javax.swing.JTextField jTextFieldOriginal;
    private javax.swing.JTextField jTextFieldTempo;
    private javax.swing.JTextField jTextFieldURL;
    // End of variables declaration//GEN-END:variables
}
